### ISSUE TITLE
Controller for subscriptions

### ISSUE THREAD

**Issue by dfmoreto** [dfmoreto/hack2save#12]
A controller to manage subscriptions must be created. It must enables creation and updating of a given subscription.
A subscription has a high dependency of a job and o creation, a cover letter must be sent by the user that is subscribing for a given job.
After creating, the user subscribed can't update it anymore. Only the users with right permissions on institution can update its status.

**Comment by saulomendonca** [comment]
users can be an owner, an administrator or an approver of one institution. Can every profile approve or reject one subscription?

**Comment by dfmoreto** [comment]
Yes. The difference between profiles is: approver only can approve and deny subscriptions, admin can update permissions and institutions details (except permissions of owner) and owner can do everything in a institution (including change administrator permission). And only one owner is possible for each institution.
