### ISSUE TITLE
Create controller of institutions

### ISSUE THREAD

**Issue by dfmoreto** [dfmoreto/hack2save#9]
Create a controller for institutions with actions that enable a CRUD operation. For now, a institution must have a name, a description and its category.

**Comment by wnascimento** [comment]
Trabalhando na issue

**Comment by dfmoreto** [comment]
@wnascimento how is it going?

**Comment by wnascimento** [comment]
@dfmoreto the issue is completed

**Comment by dfmoreto** [comment]
Oh, Sorry :grimacing:.
I'm closing this card.
